version: "2"
services:
  rocketchat:
    image: rocketchat/rocket.chat
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local6
        tag: rocketchat
    volumes:
      - /var/lib/rocketchat/data/uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://chat.laisky.com
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
    external_links:
      - mongodb:mongodb
    expose:
      - "3000"
    ports:
      - 27300:3000

  hubot:
    image: rocketchat/hubot-rocketchat
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local6
        tag: rocket-hubot
    environment:
      - ROCKETCHAT_ROOM=''
      - LISTEN_ON_ALL_PUBLIC=true
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=bot
      - ROCKETCHAT_AUTH=password
      - ROCKETCHAT_URL=http://rocketchat:3000
      - BOT_NAME=bot
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    links:
      - rocketchat:rocketchat
    ports:
      - 27301:3001

networks:
  default:
    external:
      name: docker_default
